# Site settings
title: GDSC Seoultech
email: twinklesu914@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url: gdsc-seoultech.github.io # the base hostname & protocol for your site
github_username:  gdsc-seoultech
timezone: Asia/Seoul

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  posts:
    output: true
    permalink: /posts/:path/
  seminars:
    output: true
    permalink: /seminars/:path/


